export const afghanistanProvinces = [
  { id: "AF-S", value: "Chose Your Province", label: "Chose Your Province" },
  { id: "AF-HER", value: "herat", label: "Herat" },
  { id: "AF-KAB", value: "kabul", label: "Kabul" },
  { id: "AF-BDS", value: "badakhshan", label: "Badakhshan" },
  { id: "AF-BDG", value: "badghis", label: "Badghis" },
  { id: "AF-BGL", value: "baghlan", label: "Baghlan" },
  { id: "AF-BAL", value: "balkh", label: "Balkh" },
  { id: "AF-BAM", value: "bamyan", label: "Bamyan" },
  { id: "AF-DAY", value: "daykundi", label: "Daykundi" },
  { id: "AF-FRA", value: "farah", label: "Farah" },
  { id: "AF-FYB", value: "faryab", label: "Faryab" },
  { id: "AF-GHA", value: "ghazni", label: "Ghazni" },
  { id: "AF-GHO", value: "ghor", label: "Ghor" },
  { id: "AF-HEL", value: "helmand", label: "Helmand" },
  { id: "AF-JOW", value: "jowzjan", label: "Jowzjan" },
  { id: "AF-KAN", value: "kandahar", label: "Kandahar" },
  { id: "AF-KAP", value: "kapisa", label: "Kapisa" },
  { id: "AF-KHO", value: "khost", label: "Khost" },
  { id: "AF-KNR", value: "kunar", label: "Kunar" },
  { id: "AF-KDZ", value: "kunduz", label: "Kunduz" },
  { id: "AF-LAG", value: "laghman", label: "Laghman" },
  { id: "AF-LOG", value: "logar", label: "Logar" },
  { id: "AF-NAN", value: "nangarhar", label: "Nangarhar" },
  { id: "AF-NIM", value: "nuristan", label: "Nuristan" },
  { id: "AF-PKA", value: "paktia", label: "Paktia" },
  { id: "AF-PIA", value: "paktika", label: "Paktika" },
  { id: "AF-PAN", value: "panjshir", label: "Panjshir" },
  { id: "AF-PAR", value: "parwan", label: "Parwan" },
  { id: "AF-SAM", value: "samangan", label: "Samangan" },
  { id: "AF-SAR", value: "sar-e-pol", label: "Sar-e Pol" },
  { id: "AF-TAK", value: "takhar", label: "Takhar" },
  { id: "AF-URU", value: "uruzgan", label: "Uruzgan" },
  { id: "AF-WAR", value: "wardak", label: "Wardak" },
  { id: "AF-ZAB", value: "zabul", label: "Zabul" }
];